[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && python3.11 -m pip install --upgrade pip", "cd backend && python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3.11 -m gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
